# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'FC_CreditCardList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FC_CreditCardList
  pod 'Kingfisher', '~> 7.0'
  pod 'lottie-ios'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'FirebaseCore'
  pod 'FirebaseFirestoreSwift'

end
