# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'FC_SubwayStation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FC_SubwayStation
	pod 'Alamofire', '~> 5.5'
	pod 'SnapKit', '~> 5.0.0'

end
