# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'FC_Warning' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FC_Warning
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

end
